version: '3'
services:
  groupware-whitelabel-postgres:
    image: postgres:14
    container_name: '${APP_NAME}_POSTGRES'
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - groupware-whitelabel-service

  groupware-whitelabel-adminer:
    image: adminer
    container_name: '${APP_NAME}_ADMINER'
    ports:
      - '8087:8080'
    networks:
      - groupware-whitelabel-service

  groupware-whitelabel-app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: '${APP_NAME}_APP'
    image: app-groupware-whitelabel-dev
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      POSTGRES_HOST: host.docker.internal # for mac user reference (https://stackoverflow.com/questions/33357567/econnrefused-for-postgres-on-nodejs-with-dockers)
    ports:
      - 3000:3000
    depends_on:
      - groupware-whitelabel-postgres
    networks:
      - groupware-whitelabel-service

networks:
  groupware-whitelabel-service:

volumes:
  pg_data:


  # Notes if any errors occur during the build process, you can use the following documentation to troubleshoot:
  # error bcrypt : https://stackoverflow.com/questions/59470406/how-to-solve-could-not-find-any-python-installation-to-use-with-docker-node-al